/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversityRouteImport } from './routes/university'
import { Route as ToolsDictionaryDotjsonRouteImport } from './routes/tools-dictionary[.]json'
import { Route as ToolsApiDotjsonRouteImport } from './routes/tools-api[.]json'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchApiDotjsonRouteImport } from './routes/search-api[.]json'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ExclusiveApiDotjsonRouteImport } from './routes/exclusive-api[.]json'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolSlugRouteImport } from './routes/tool/$slug'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'

const UniversityRoute = UniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDictionaryDotjsonRoute = ToolsDictionaryDotjsonRouteImport.update({
  id: '/tools-dictionary.json',
  path: '/tools-dictionary.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsApiDotjsonRoute = ToolsApiDotjsonRouteImport.update({
  id: '/tools-api.json',
  path: '/tools-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchApiDotjsonRoute = SearchApiDotjsonRouteImport.update({
  id: '/search-api.json',
  path: '/search-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusiveApiDotjsonRoute = ExclusiveApiDotjsonRouteImport.update({
  id: '/exclusive-api.json',
  path: '/exclusive-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSlugRoute = ToolSlugRouteImport.update({
  id: '/tool/$slug',
  path: '/tool/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/exclusive-api.json': typeof ExclusiveApiDotjsonRoute
  '/ranking': typeof RankingRoute
  '/search-api.json': typeof SearchApiDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/tools-api.json': typeof ToolsApiDotjsonRoute
  '/tools-dictionary.json': typeof ToolsDictionaryDotjsonRoute
  '/university': typeof UniversityRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tool/$slug': typeof ToolSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/exclusive-api.json': typeof ExclusiveApiDotjsonRoute
  '/ranking': typeof RankingRoute
  '/search-api.json': typeof SearchApiDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/tools-api.json': typeof ToolsApiDotjsonRoute
  '/tools-dictionary.json': typeof ToolsDictionaryDotjsonRoute
  '/university': typeof UniversityRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tool/$slug': typeof ToolSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/exclusive-api.json': typeof ExclusiveApiDotjsonRoute
  '/ranking': typeof RankingRoute
  '/search-api.json': typeof SearchApiDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/tools-api.json': typeof ToolsApiDotjsonRoute
  '/tools-dictionary.json': typeof ToolsDictionaryDotjsonRoute
  '/university': typeof UniversityRoute
  '/category/$slug': typeof CategorySlugRoute
  '/tool/$slug': typeof ToolSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advertise'
    | '/auth'
    | '/compare'
    | '/exclusive-api.json'
    | '/ranking'
    | '/search-api.json'
    | '/sitemap.xml'
    | '/submit'
    | '/tools-api.json'
    | '/tools-dictionary.json'
    | '/university'
    | '/category/$slug'
    | '/tool/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advertise'
    | '/auth'
    | '/compare'
    | '/exclusive-api.json'
    | '/ranking'
    | '/search-api.json'
    | '/sitemap.xml'
    | '/submit'
    | '/tools-api.json'
    | '/tools-dictionary.json'
    | '/university'
    | '/category/$slug'
    | '/tool/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advertise'
    | '/auth'
    | '/compare'
    | '/exclusive-api.json'
    | '/ranking'
    | '/search-api.json'
    | '/sitemap.xml'
    | '/submit'
    | '/tools-api.json'
    | '/tools-dictionary.json'
    | '/university'
    | '/category/$slug'
    | '/tool/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdvertiseRoute: typeof AdvertiseRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ExclusiveApiDotjsonRoute: typeof ExclusiveApiDotjsonRoute
  RankingRoute: typeof RankingRoute
  SearchApiDotjsonRoute: typeof SearchApiDotjsonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  ToolsApiDotjsonRoute: typeof ToolsApiDotjsonRoute
  ToolsDictionaryDotjsonRoute: typeof ToolsDictionaryDotjsonRoute
  UniversityRoute: typeof UniversityRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ToolSlugRoute: typeof ToolSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/university': {
      id: '/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof UniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools-dictionary.json': {
      id: '/tools-dictionary.json'
      path: '/tools-dictionary.json'
      fullPath: '/tools-dictionary.json'
      preLoaderRoute: typeof ToolsDictionaryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools-api.json': {
      id: '/tools-api.json'
      path: '/tools-api.json'
      fullPath: '/tools-api.json'
      preLoaderRoute: typeof ToolsApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-api.json': {
      id: '/search-api.json'
      path: '/search-api.json'
      fullPath: '/search-api.json'
      preLoaderRoute: typeof SearchApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusive-api.json': {
      id: '/exclusive-api.json'
      path: '/exclusive-api.json'
      fullPath: '/exclusive-api.json'
      preLoaderRoute: typeof ExclusiveApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$slug': {
      id: '/tool/$slug'
      path: '/tool/$slug'
      fullPath: '/tool/$slug'
      preLoaderRoute: typeof ToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdvertiseRoute: AdvertiseRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ExclusiveApiDotjsonRoute: ExclusiveApiDotjsonRoute,
  RankingRoute: RankingRoute,
  SearchApiDotjsonRoute: SearchApiDotjsonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  ToolsApiDotjsonRoute: ToolsApiDotjsonRoute,
  ToolsDictionaryDotjsonRoute: ToolsDictionaryDotjsonRoute,
  UniversityRoute: UniversityRoute,
  CategorySlugRoute: CategorySlugRoute,
  ToolSlugRoute: ToolSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
