CREATE TYPE public.app_role AS ENUM ('admin', 'moderator', 'user');
CREATE TYPE public.review_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TABLE public.categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL UNIQUE, slug TEXT NOT NULL UNIQUE, icon TEXT, tool_count INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
GRANT SELECT ON public.categories TO anon, authenticated; GRANT ALL ON public.categories TO service_role;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can view categories" ON public.categories FOR SELECT USING (true);
CREATE TABLE public.ai_tools (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, official_url TEXT, logo_url TEXT, short_description TEXT NOT NULL DEFAULT '', overview TEXT, features JSONB NOT NULL DEFAULT '[]'::jsonb, category_ids UUID[] NOT NULL DEFAULT '{}', pricing_model TEXT NOT NULL DEFAULT 'Freemium', has_free_plan BOOLEAN NOT NULL DEFAULT false, platforms TEXT[] NOT NULL DEFAULT ARRAY['Web'], languages TEXT[] NOT NULL DEFAULT ARRAY['English'], use_cases JSONB NOT NULL DEFAULT '[]'::jsonb, pros JSONB NOT NULL DEFAULT '[]'::jsonb, cons JSONB NOT NULL DEFAULT '[]'::jsonb, similar_tool_ids UUID[] NOT NULL DEFAULT '{}', date_added TIMESTAMPTZ NOT NULL DEFAULT now(), popularity_score NUMERIC(8,2) NOT NULL DEFAULT 0, is_featured BOOLEAN NOT NULL DEFAULT false, is_trending BOOLEAN NOT NULL DEFAULT false, status public.review_status NOT NULL DEFAULT 'pending', verification_notes TEXT, discovery_source TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
GRANT SELECT ON public.ai_tools TO anon, authenticated; GRANT ALL ON public.ai_tools TO service_role;
ALTER TABLE public.ai_tools ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can view approved tools" ON public.ai_tools FOR SELECT USING (status = 'approved');
CREATE INDEX ai_tools_search_idx ON public.ai_tools USING gin (to_tsvector('english', name || ' ' || short_description || ' ' || COALESCE(overview, '')));
CREATE INDEX ai_tools_status_date_idx ON public.ai_tools (status, date_added DESC);
CREATE INDEX ai_tools_popularity_idx ON public.ai_tools (popularity_score DESC);
CREATE TABLE public.advertisements (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), full_name TEXT NOT NULL, email TEXT NOT NULL, tool_name TEXT NOT NULL, website_url TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, whatsapp TEXT, telegram TEXT, placement TEXT NOT NULL, payment_status TEXT NOT NULL DEFAULT 'pending_manual_confirmation', status public.review_status NOT NULL DEFAULT 'pending', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
GRANT INSERT ON public.advertisements TO anon, authenticated; GRANT SELECT, UPDATE, DELETE ON public.advertisements TO authenticated; GRANT ALL ON public.advertisements TO service_role;
ALTER TABLE public.advertisements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can submit an advertisement" ON public.advertisements FOR INSERT WITH CHECK (status = 'pending' AND payment_status = 'pending_manual_confirmation');
CREATE TABLE public.tool_discoveries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tool_name TEXT NOT NULL, candidate_url TEXT, source_url TEXT NOT NULL, source_type TEXT NOT NULL, extracted_data JSONB NOT NULL DEFAULT '{}'::jsonb, confidence_score NUMERIC(5,2) NOT NULL DEFAULT 0, status public.review_status NOT NULL DEFAULT 'pending', reviewed_by UUID, reviewed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tool_discoveries TO authenticated; GRANT ALL ON public.tool_discoveries TO service_role;
ALTER TABLE public.tool_discoveries ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.user_roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL, role public.app_role NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(user_id, role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role public.app_role) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;
CREATE POLICY "Users can view their own roles" ON public.user_roles FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Admins manage tools" ON public.ai_tools FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins manage categories" ON public.categories FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins manage advertisements" ON public.advertisements FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins manage discoveries" ON public.tool_discoveries FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE OR REPLACE FUNCTION public.update_updated_at_column() RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;
CREATE TRIGGER update_categories_updated_at BEFORE UPDATE ON public.categories FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_ai_tools_updated_at BEFORE UPDATE ON public.ai_tools FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_advertisements_updated_at BEFORE UPDATE ON public.advertisements FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_tool_discoveries_updated_at BEFORE UPDATE ON public.tool_discoveries FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();